### ISSUE TITLE
c-style compile didn't work in watch mode

### ISSUE THREAD

**Issue by biyingshuai** [design-to-release/cosmic#97]
**Describe the bug**
While using custom module css in c-style,   watch task cannot detect the module css file changed

**To Reproduce**
1. add a c-style in component
2. use relative import module css
3. npm run watch
4. After electron ran, change the module css file content

**Expected behavior**
1. compile terminal window should output log for compiling changed files
2. electron was reloaded by HMR

**Screenshots**
None of above phenomena happened

**Comment by qiansc** [comment]
dont use c-style any more
